<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2020, 2022 Contributors to the Eclipse Foundation.
    All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

-->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.jboss</groupId>
        <artifactId>jboss-parent</artifactId>
        <version>51</version>
    </parent>

    <groupId>org.jboss.spec.jakarta.el</groupId>
    <artifactId>el-parent</artifactId>
    <packaging>pom</packaging>
    <version>6.0.3.Final-SNAPSHOT</version>

    <name>WildFly Jakarta Expression Language API -- Parent</name>
    <description>Jakarta Expression Language API for use in a WildFly server</description>
    <url>https://github.com/wildfly/jboss-jakarta-el-api_spec</url>

    <licenses>
        <license>
            <name>EPL 2.0</name>
            <url>http://www.eclipse.org/legal/epl-2.0</url>
            <distribution>repo</distribution>
        </license>
        <license>
            <name>GPL2 w/ CPE</name>
            <url>https://www.gnu.org/software/classpath/license.html</url>
            <distribution>repo</distribution>
        </license>
        <license>
            <name>Apache 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <connection>scm:git:git@github.com:wildfly/jboss-jakarta-el-api_spec.git</connection>
        <developerConnection>scm:git:git@github.com:wildfly/jboss-jakarta-el-api_spec.git</developerConnection>
        <url>https://github.com/wildfly/jboss-jakarta-el-api_spec</url>
        <tag>HEAD</tag>
    </scm>

    <issueManagement>
        <system>github</system>
        <url>https://github.com/wildfly/jboss-jakarta-el-api_spec/issues</url>
    </issueManagement>

    <developers>
        <developer>
            <id>wildfly.org</id>
            <name>WildFly Community</name>
            <organization>wildfly.org</organization>
            <organizationUrl>https://wildfly.org</organizationUrl>
            <email>wildfly-dev@lists.jboss.org</email>
        </developer>
        <developer>
            <id>jakarta-ee4j-el</id>
            <name>Jakarta Expression Language Developers</name>
            <organization>Eclipse Foundation</organization>
            <email>el-dev@eclipse.org</email>
        </developer>
    </developers>
    <contributors>
        <contributor>
            <name>Jakarta Expression Language Contributors</name>
            <email>el-dev@eclipse.org</email>
            <url>https://github.com/eclipse-ee4j/el-ri/graphs/contributors</url>
        </contributor>
    </contributors>

    <properties>
        <!-- Settings used by the jboss-release profile to drive the nxrm3-maven-plugin -->
        <nexus.repository.staging>wildfly-staging</nexus.repository.staging>
        <nexus.repository.release>releases</nexus.repository.release> <!-- this is the value from jboss-parent, so we could drop it here -->
        <nexus.staging.tag>jboss-jakarta-el-api_spec-${project.version}</nexus.staging.tag>
    </properties>

    <modules>
        <module>api</module>
    </modules>

    <build>
        <plugins>
            <!-- Sets minimal Maven version -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <id>enforce-maven</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <requireMavenVersion>
                                    <version>3.6.0</version>
                                </requireMavenVersion>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
